/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.InsertScoresData;
import Controller.SmileGameEngine;
import Model.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author ravin
 */
public class GamePage extends javax.swing.JFrame {

    SmileGameEngine myGame = null;
    BufferedImage currentGame = null;
    Timer timer;
    int second, minute;
    int noOfAttempts = 0;
    String ddSecond, ddMinute;
    User newUser;
    int score;
    String game = "Smile";
    InsertScoresData scoresData = new InsertScoresData();

    DecimalFormat dFormat = new DecimalFormat("00");

    /**
     * Creates new form GamePage
     */

    public GamePage(User user, int attempt) {
        newUser = user;
        noOfAttempts = attempt;
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        //System.out.println("After Init");
        myGame = new SmileGameEngine(user.getUsername());
        currentGame = myGame.nextGame();
        ImageIcon ii = new ImageIcon(currentGame);
        questionField.setIcon(ii);
        
        //score_Smile.setText(String.valueOf(0));
        attemptsField.setText(noOfAttempts+"/5");
        callTimer();

    }

    public void countdownTimer() {
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                second--;
                ddSecond = dFormat.format(second);
                ddMinute = dFormat.format(minute);
                timerSmile.setText(ddMinute + ":" + ddSecond);

                if (second == -1) {
                    second = 59;
                    minute--;
                    ddSecond = dFormat.format(second);
                    ddMinute = dFormat.format(minute);
                    timerSmile.setText(ddMinute + ":" + ddSecond);
                }
                if (minute == 0 && second == 0) {
                    timer.stop();
                    noOfAttempts++;
                    loadNewGame();
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        questionField = new javax.swing.JLabel();
        InputField_Smile = new javax.swing.JTextField();
        btnSubmit_Smile = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        score_Smile = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        attemptsField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        timerSmile = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Smile Game");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        questionField.setText("jLabel3");
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 660, 360));

        InputField_Smile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        InputField_Smile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputField_Smile.setText("input");
        InputField_Smile.setBorder(null);
        InputField_Smile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputField_SmileMouseClicked(evt);
            }
        });
        getContentPane().add(InputField_Smile, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 100, 40));

        btnSubmit_Smile.setBackground(new java.awt.Color(0, 51, 255));
        btnSubmit_Smile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit_Smile.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit_Smile.setText("Submit");
        btnSubmit_Smile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit_SmileActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit_Smile, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 600, 130, 40));

        score_Smile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        score_Smile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score_Smile.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(score_Smile, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(score_Smile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Here :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attempts :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        attemptsField.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        attemptsField.setForeground(new java.awt.Color(255, 255, 255));
        attemptsField.setText("0/5");
        getContentPane().add(attemptsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(115, 50));

        timerSmile.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        timerSmile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timerSmile.setText("00:00");
        timerSmile.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerSmile, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timerSmile, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravin\\Documents\\NetBeansProjects\\SmileBuddy\\src\\main\\java\\resources\\mainPageBG.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmit_SmileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit_SmileActionPerformed
        String input = InputField_Smile.getText();
        int solution = Integer.parseInt(input);
        boolean correct = myGame.checkSolution(solution);
        score = myGame.getScore();
        if (correct) {
            timer.stop();
            System.out.println("Solution is Correct!");
            currentGame = myGame.nextGame();
            ImageIcon icon = new ImageIcon(currentGame);
            questionField.setIcon(icon);
            score_Smile.setText(String.valueOf(score));
            callTimer();
        } else {
            System.out.println("Incorrect Solution!");
            score_Smile.setText(String.valueOf(score));
            timer.stop();
            noOfAttempts++;
            loadNewGame();
            
        }
    }//GEN-LAST:event_btnSubmit_SmileActionPerformed

    private void InputField_SmileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputField_SmileMouseClicked
        InputField_Smile.setText(null);
    }//GEN-LAST:event_InputField_SmileMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            scoresData.insertScore(newUser.getUsername(), score, game);
        } catch (SQLException ex) {
            System.out.println("Inserting Unsuccessful when closing the window!");
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GamePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputField_Smile;
    private javax.swing.JLabel attemptsField;
    private javax.swing.JButton btnSubmit_Smile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel questionField;
    private javax.swing.JLabel score_Smile;
    private javax.swing.JLabel timerSmile;
    // End of variables declaration//GEN-END:variables

    private void callTimer() {
        timerSmile.setText("01:00");
        second = 0;
        minute = 1;
        countdownTimer();
        timer.start();
    }
    
    public void loadNewGame(){
        attemptsField.setText(noOfAttempts+"/5");
        if (noOfAttempts == 6) {
            try {
                scoresData.insertScore(newUser.getUsername(), score, game);
            } catch (SQLException ex) {
                System.out.println("Inserting unsuccessful when attempts exceeded!");
            }
            dispose();
            MainMenu mainMenu = new MainMenu(newUser);
            mainMenu.setVisible(true);
        }
        else{
            currentGame = myGame.nextGame();
            ImageIcon nxtIcon = new ImageIcon(currentGame);
            questionField.setIcon(nxtIcon);
            callTimer();
            
        }
        
    }
}
