/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.User;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author ravin
 */
public class GameMenu extends javax.swing.JFrame {

    User currentUser;

    /**
     * Creates new form GameMenu
     */
    public GameMenu(User user) {
        initComponents();
        currentUser = user;
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        smileGame = new javax.swing.JButton();
        heartGame = new javax.swing.JButton();
        starGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        smileGame.setBackground(new java.awt.Color(0, 0, 255));
        smileGame.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        smileGame.setForeground(new java.awt.Color(255, 255, 255));
        smileGame.setText("SMILE GAME");
        smileGame.setBorder(null);
        smileGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smileGameActionPerformed(evt);
            }
        });
        getContentPane().add(smileGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 200, 50));

        heartGame.setBackground(new java.awt.Color(0, 0, 255));
        heartGame.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heartGame.setForeground(new java.awt.Color(255, 255, 255));
        heartGame.setText("HEART GAME");
        heartGame.setBorder(null);
        heartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartGameActionPerformed(evt);
            }
        });
        getContentPane().add(heartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 200, 50));

        starGame.setBackground(new java.awt.Color(0, 0, 255));
        starGame.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        starGame.setForeground(new java.awt.Color(255, 255, 255));
        starGame.setText("STAR GAME");
        starGame.setBorder(null);
        starGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starGameActionPerformed(evt);
            }
        });
        getContentPane().add(starGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravin\\Documents\\NetBeansProjects\\SmileBuddy\\src\\main\\java\\resources\\Login.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 826, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smileGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smileGameActionPerformed
        int attemps = 1;
        GamePage gamePage = new GamePage(currentUser, attemps);
        gamePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_smileGameActionPerformed

    private void heartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartGameActionPerformed
        int attempt = 1;
        HeartGamePage heartGamePage = new HeartGamePage(currentUser, attempt);
        heartGamePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_heartGameActionPerformed

    private void starGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_starGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new GameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton heartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton smileGame;
    private javax.swing.JButton starGame;
    // End of variables declaration//GEN-END:variables
}
