/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DB_Connection;
import Model.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ravin
 */
public class Registration extends JFrame{

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rUsername = new javax.swing.JTextField();
        rEmail = new javax.swing.JTextField();
        rPassword = new javax.swing.JPasswordField();
        rConfirmPasword = new javax.swing.JPasswordField();
        rBtnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(826, 676));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SignUp");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        rUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rUsername.setForeground(new java.awt.Color(204, 204, 204));
        rUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rUsername.setText("Username");
        rUsername.setBorder(null);
        rUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rUsernameMouseClicked(evt);
            }
        });
        getContentPane().add(rUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 250, 70));

        rEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rEmail.setForeground(new java.awt.Color(204, 204, 204));
        rEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rEmail.setText("Email");
        rEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rEmailMouseClicked(evt);
            }
        });
        getContentPane().add(rEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 250, 70));

        rPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rPassword.setForeground(new java.awt.Color(204, 204, 204));
        rPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rPassword.setText("jPasswordField1");
        rPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(rPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 250, 70));

        rConfirmPasword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rConfirmPasword.setForeground(new java.awt.Color(204, 204, 204));
        rConfirmPasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rConfirmPasword.setText("Confirm Password");
        rConfirmPasword.setBorder(null);
        rConfirmPasword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rConfirmPaswordMouseClicked(evt);
            }
        });
        getContentPane().add(rConfirmPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 250, 70));

        rBtnRegister.setBackground(new java.awt.Color(0, 0, 255));
        rBtnRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rBtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        rBtnRegister.setText("Register");
        rBtnRegister.setBorder(null);
        rBtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(rBtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ravin\\Documents\\NetBeansProjects\\SmileBuddy\\src\\main\\java\\resources\\Login.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 826, 676));

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 680));

        setBounds(0, 0, 842, 685);
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnRegisterActionPerformed
        try {
            // TODO add your handling code here:
            registerUser();
        } catch (SQLException ex) {
            System.out.println("Registration :"+ex);
        }
    }//GEN-LAST:event_rBtnRegisterActionPerformed

    private void rUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rUsernameMouseClicked
        rUsername.setText(null);
        rUsername.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_rUsernameMouseClicked

    private void rEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rEmailMouseClicked
        rEmail.setText(null);
        rEmail.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_rEmailMouseClicked

    private void rPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rPasswordMouseClicked
        rPassword.setText(null);
        rPassword.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_rPasswordMouseClicked

    private void rConfirmPaswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rConfirmPaswordMouseClicked
        rConfirmPasword.setText(null);
        rConfirmPasword.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_rConfirmPaswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

 
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rBtnRegister;
    private javax.swing.JPasswordField rConfirmPasword;
    private javax.swing.JTextField rEmail;
    private javax.swing.JPasswordField rPassword;
    private javax.swing.JTextField rUsername;
    private javax.swing.JPanel registerPanel;
    // End of variables declaration//GEN-END:variables

    private void registerUser() throws SQLException {
        String username = rUsername.getText();
        String email = rEmail.getText();
        String password = String.valueOf(rPassword.getPassword());
        String cPassword = String.valueOf(rConfirmPasword.getPassword());
        
        if (username.isEmpty() || email.isEmpty() || password.isEmpty()|| cPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please Enter All Fields",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!password.equals(cPassword)) {
            JOptionPane.showMessageDialog(this,
                    "Confirm Password does not match!",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        User user = new User();
        //User newUser = new User();
        user.setUsername(username);
        user.setEmail(email);
        user.setPassword(password);
        
        int response = addUserToDatabase(user);
        
        if (response == 1) {
            //navigation here
            System.out.println("Successful Registration of : "+user.getUsername());
            Login login = new Login();
            login.setVisible(true);
            dispose();
        }else{
            System.out.println("Registration Unsuccessful!");
            JOptionPane.showMessageDialog(this,
                    "Failed to Register new User",
                    "Try Again",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    private int addUserToDatabase(User user) throws SQLException {
        DB_Connection obj = new DB_Connection();
        Connection connection = obj.getConnection();
        PreparedStatement ps = null;
        int response;
        
        try {
            String query = "INSERT INTO users(username,email,password) VALUES(?,?,?)";
            
            ps = connection.prepareStatement(query);
            ps.setString(1, user.getUsername());
            ps.setString(2, user.getEmail());
            ps.setString(3, user.getPassword());
            ps.executeUpdate();
            response = 1;
        } catch (Exception e) {
            System.out.println("Some Error when Inserting Values to DB :");
            System.err.println(e);
            response = 0;
        }
        connection.close();
        ps.close();
        
        return response;
    }
}
